# Generated by Django 4.1.5 on 2023-01-29 14:45
import datetime
from django.db import migrations, models
import django.utils.datetime_safe
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='контактная почта')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_topic', models.CharField(max_length=350, verbose_name='Тема письма')),
                ('letter_body', models.TextField(verbose_name='Содержание письма')),
            ],
        ),
        migrations.CreateModel(
            name='MailigTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')),
                ('status', models.CharField(max_length=50, verbose_name='статус попытки')),
                ('answer', models.CharField(blank=True, null=True, max_length=250, verbose_name='ответ сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_mailing', models.DateTimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('once_a_day', 'раз в день'), ('once_a week', 'раз в неделю'), ('once_a_month', 'раз в месяц')], default='once_a_week', max_length=50, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='completed', max_length=50, verbose_name='статус рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Начальная дата')),
                ('end_date', models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='конечная дата')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursach.client', verbose_name='клиент')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursach.letter', verbose_name='сообщение')),
            ],
        ),
    ]

